# SPDX-FileCopyrightText: 2026 Lasath Fernando <devel@lasath.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Base Arch Linux image for Kapsule containers.
# Other images (e.g. kapsule-dev) inherit this via Dependencies=/BaseTrees=.

[Output]
Format=directory

[Content]
Packages=
        base
        diffutils
        file
        gettext
        grep
        grml-zsh-config
        groff
        gzip
        inetutils
        iproute2
        iputils
        iptables-nft
        less
        licenses
        logrotate
        man-db
        man-pages
        nano
        procps-ng
        psmisc
        sed
        sudo
        sysfsutils
        systemd-sysvcompat
        tar
        texinfo
        vi
        which
