# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 Lasath Fernando <devel@lasath.org>

include:
  - project: sysadmin/ci-utilities
    file:
      - /gitlab-templates/reuse-lint.yml
      - /gitlab-templates/blocks/workflow.yml

stages:
  - validate
  - build

.build_common: &build_common
  stage: build
  image: storage.kde.org/vm-images/kde-linux-builder
  tags:
    - VM
    - amd64
  id_tokens:
    MINIO_OIDC:
      aud: https://tokens.kde.org
  variables:
    RUNNER_AFTER_SCRIPT_TIMEOUT: 1h
  artifacts:
    expire_in: 7 days
    when: always
    paths:
      - out/
      - streams/
  script:
    - sudo pacman -Sy --noconfirm python-yaml jq squashfs-tools mkosi
    - mkdir -p out streams
    - sudo images/build-image.sh out/
    - python3 images/generate-simplestreams.py images/ out/ streams/

build-images:
  <<: *build_common
  rules:
    - if: $CI_MERGE_REQUEST_DRAFT == "true"
      when: manual
    - if: $CI_COMMIT_BRANCH =~ /^work\//
      when: manual
    - if: $CI_COMMIT_REF_PROTECTED != 'true' || $CI_DEFAULT_BRANCH != $CI_COMMIT_REF_NAME || $CI_PROJECT_PATH != 'kde-linux/kapsule'
      changes:
        - images/**/*
        - .gitlab-ci.yml
      when: always
  after_script:
    - images/upload-images.sh "ci-artifacts/${CI_PROJECT_PATH}/j/${CI_JOB_ID}"

build-images+publish:
  <<: *build_common
  rules:
    - if: $CI_COMMIT_REF_PROTECTED == 'true' && $CI_DEFAULT_BRANCH == $CI_COMMIT_REF_NAME && $CI_PROJECT_PATH == 'kde-linux/kapsule'
      changes:
        - images/**/*
        - .gitlab-ci.yml
      when: always
  script:
    - sudo pacman -Sy --noconfirm python-yaml jq squashfs-tools mkosi
    - mkdir -p out streams
    - sudo images/build-image.sh out/
    - python3 images/generate-simplestreams.py images/ out/ streams/
    - images/upload-images.sh "ci-artifacts/${CI_PROJECT_PATH}/j/${CI_JOB_ID}"

build-sysext:
  stage: build
  image: storage.kde.org/vm-images/kde-linux-builder
  tags:
    - VM
    - amd64
  id_tokens:
    MINIO_OIDC:
      aud: https://tokens.kde.org
  variables:
    RUNNER_AFTER_SCRIPT_TIMEOUT: 1h
  artifacts:
    expire_in: 7 days
    when: always
    paths:
      - sysext/mkosi.output/kapsule.raw
  rules:
    - if: $CI_MERGE_REQUEST_DRAFT == "true"
      when: manual
    - if: $CI_COMMIT_BRANCH =~ /^work\//
      when: manual
    - when: always
  script:
    - sudo pacman -Sy --noconfirm mkosi erofs-utils
    - sudo mkosi --directory=sysext build
  after_script:
    - scripts/upload-sysext.sh "ci-artifacts/${CI_PROJECT_PATH}/sysext/j/${CI_JOB_ID}" sysext/mkosi.output/kapsule.raw || true
