# SPDX-FileCopyrightText: 2026 Lasath Fernando <devel@lasath.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Base Arch Linux tree used as the build environment for the kapsule sysext.
# This is a dependency of the main sysext image and is not shipped.

[Output]
Format=directory

[Content]
Packages=
        base
        python
        base-devel
        cmake
        ninja
        git
        python-pip
        extra-cmake-modules
        qt6-base
        kcoreaddons
        ki18n
        kconfig
        qcoro
        kio
        kcmutils
