#!/bin/sh

# SPDX-FileCopyrightText: 2026 Lasath Fernando <devel@lasath.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Receives DNS resolver configuration on stdin and writes it to resolv.conf
cat > /etc/resolv.conf
